#!/usr/bin/env php

<?php

// 1. Встановити базовий шлях

use SimplePhpFramework\Console\Kernel;

define('BASE_PATH', dirname(__FILE__));

// 2. Додати autoloader

require_once BASE_PATH . '/vendor/autoload.php';

// 3. Додати контейнер

/** @var \League\Container\Container $container */
$container = require BASE_PATH . '/config/services.php';

// 4. Отримати Kernel консолі з контейнера

$kernel = $container->get(Kernel::class);

// 5. Викликати метод handle у Kernel, повернути код статусу консольної програми

$status = $kernel->handle();

// 6. Вийти із цим статусом.

exit ($status);